package src.Absyn; // Java Package generated by the BNF Converter.

import src.TypeException;

public class Ass extends Stmt {
  public final String ident_;
  public final Expr expr_;
  public Ass(String p1, Expr p2) { ident_ = p1; expr_ = p2; }

  public <R,A> R accept(src.Absyn.Stmt.Visitor<R,A> v, A arg) throws TypeException { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof src.Absyn.Ass) {
      src.Absyn.Ass x = (src.Absyn.Ass)o;
      return this.ident_.equals(x.ident_) && this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ident_.hashCode())+this.expr_.hashCode();
  }


}
