package src.Absyn; // Java Package generated by the BNF Converter.

import src.TypeException;

public class Program extends Prog {
  public final ListTopDef listtopdef_;
  public Program(ListTopDef p1) { listtopdef_ = p1; }

  public <R,A> R accept(src.Absyn.Prog.Visitor<R,A> v, A arg) throws TypeException { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof src.Absyn.Program) {
      src.Absyn.Program x = (src.Absyn.Program)o;
      return this.listtopdef_.equals(x.listtopdef_);
    }
    return false;
  }

  public int hashCode() {
    return this.listtopdef_.hashCode();
  }


}
