package src.Absyn; // Java Package generated by the BNF Converter.

import src.TypeException;

public class SExp extends Stmt {
  public final Expr expr_;
  public SExp(Expr p1) { expr_ = p1; }

  public <R,A> R accept(src.Absyn.Stmt.Visitor<R,A> v, A arg) throws TypeException { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof src.Absyn.SExp) {
      src.Absyn.SExp x = (src.Absyn.SExp)o;
      return this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return this.expr_.hashCode();
  }


}
