package src.Absyn; // Java Package generated by the BNF Converter.

import src.TypeException;

public abstract class Stmt implements java.io.Serializable {
  public abstract <R,A> R accept(Stmt.Visitor<R,A> v, A arg) throws TypeException, src.TypeException;
  public interface Visitor <R,A> {
    public R visit(src.Absyn.Empty p, A arg);
    public R visit(src.Absyn.BStmt p, A arg) throws TypeException;
    public R visit(src.Absyn.Decl p, A arg) throws TypeException;
    public R visit(src.Absyn.Ass p, A arg) throws TypeException;
    public R visit(src.Absyn.Incr p, A arg) throws TypeException;
    public R visit(src.Absyn.Decr p, A arg) throws TypeException;
    public R visit(src.Absyn.Ret p, A arg) throws TypeException;
    public R visit(src.Absyn.VRet p, A arg) throws TypeException;
    public R visit(src.Absyn.Cond p, A arg) throws TypeException;
    public R visit(src.Absyn.CondElse p, A arg) throws TypeException;
    public R visit(src.Absyn.While p, A arg) throws TypeException;
    public R visit(src.Absyn.SExp p, A arg) throws TypeException;

  }

}
