package src.Absyn; // Java Package generated by the BNF Converter.

import src.TypeException;

public class VRet extends Stmt {
  public VRet() { }

  public <R,A> R accept(src.Absyn.Stmt.Visitor<R,A> v, A arg) throws TypeException { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof src.Absyn.VRet) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
